#!/bin/bash

echo "==========================================="
echo "Settings Table Migration for Supabase"
echo "==========================================="
echo ""
echo "The settings table is missing from your new Supabase project."
echo "This table stores the backend endpoint URL and proxy credentials."
echo ""
echo "To fix this, follow these steps:"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/pffapmqqswcmndlvkjrs/sql/new"
echo ""
echo "2. Copy and paste the SQL below:"
echo ""
echo "==========================================="
cat supabase/migrations/20260121000000_add_settings_table.sql
echo ""
echo "==========================================="
echo ""
echo "3. Click 'RUN' to execute the migration"
echo ""
echo "4. Verify the table was created by checking:"
echo "   https://supabase.com/dashboard/project/pffapmqqswcmndlvkjrs/editor"
echo ""
echo "This will:"
echo "  - Create the settings table"
echo "  - Enable Row Level Security"
echo "  - Insert default backend endpoint for your user"
echo ""
